### PR TITLE
Simplify elevation matching

### LINKED ISSUE #8: Elevation matching can be simplified
When I was originally implementing elevation, I assumed there would be multiple elevation graphics per tile (since that's the case with border style 1 terrain border rendering). So I implemented it with that assumption, and then it turned out wrong.

All of the elevation graphics are currently wrapped in a Vec when they can just be single:
https://github.com/angered-ghandi/OpenAOE/blob/master/src/terrain/elevation.rs#L119

This can be refactored so that only a single graphic is stored (and then the for loop in the rendering code eliminated).

### PR DESCRIPTION
**Pull request by Xinayder**
Closes #8

### CODE REVIEW

File: src/terrain/elevation.rs [hunk 1]
```diff
@@ -80,11 +80,11 @@ impl ElevationGraphic {
 
 pub struct ElevationMatch {
     matcher: u8,
-    pub elevation_graphics: Vec<ElevationGraphic>,
+    pub elevation_graphics: ElevationGraphic,
```
Comment (angered-ghandi) [inline src/terrain/elevation.rs:83]: Rename to elevation_graphic.

**Comment by angered-ghandi** [comment]
I'm doing a large refactor in this area, so I'll pull this in as is.
